### ISSUE TITLE
Using Grunt and Bower with JQuery and Angular

### ISSUE THREAD

**Issue by ashesnz** [peteclodi/angular-custom-range-slider#23]
Hello there, 

First of all fantastic work on this library!

However, I'm having an issue using it with bower and grunt. Grunt automagically organises my bower_components js files and injects them into my index.htm file. In which case jquery.js is listed BEFORE angular.js, this causes the range slider library to break.

The problem is  angular.element("<div></div>") uses the JQuery library rather than JQLite (angular), I could shift my files around however grunt keeps organising my files so jquery is always listed before angularjs (which is very frutrasting!)

Is the a way in which you could force angular.element to use JQLite within your library?

**Comment by peteclodi** [comment]
My library was written so that it does not have a dependency on jQuery. If you remove your code's jQuery requirement, through your bower.json, you should be able to use this control.

If you have a hard requirement for jQuery then I will need more information to understand what is breaking as I never tested this control with jQuery. Could you provide a line number for the code that is breaking, if possible; and your html code for the <angular-custom-range-slider> element.

**Comment by ashesnz** [comment]
Hello there Pete, Thanks for the quick reply!

Unfortunately I have a lot of other plugins dependent on JQuery at the time begin =(

However I attached a screenshot of the problem and the error I'm getting is

TypeError: Cannot read property 'prevPageX' of undefined
![jqueryissue](https://cloud.githubusercontent.com/assets/3003043/3973398/3b95ff26-27e7-11e4-8378-429664d8e510.png)

Much appreciated with any help you can provide!
Ashwin.

**Comment by peteclodi** [comment]
I'll look into this as soon as I am able, and I'll get back to you.

**Comment by ashesnz** [comment]
Just to further note, I've just tested this with the demo you had provided in Github, by doing a 'bower install jquery' (which installs jquery above angular with Grunt)

And I haven't changed any of the HTML Code and has the exact same issue as what I'm having.

Thank you so much!
